apiVersion: apps/v1
kind: Deployment
metadata:
  name: huakai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: huakai
  template:
    metadata:
      labels:
        app: huakai
    spec:
      containers:
      - image: okteto.dev/huakai:latest
        name: huakai
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "f6f15034-0dc8-11ed-861d-0242ac120002"
        - name: Vless_Path
          value: "/vltgrfg55"
        - name: Vmess_UUID
          value: "f6f15034-0dc8-11ed-861d-0242ac120002"
        - name: Vmess_Path
          value: "/vm6hyjuhy66"
        - name: Share_Path
          value: "/v2link"
